"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.test_3 = void 0;
/**
 * This is auto generated by `tsdk`.
 * Don't edit this file.
 */
/** This line auto generated by `tsdk` and this will be removed if have content. */
exports.test_3 = 4;
